### ISSUE TITLE
gemini-controller panics on K8s v1.22.6

### ISSUE THREAD

**Issue by vovinacci** [FairwindsOps/gemini#52]
### What happened?

All worked just fine on various K8s v1.21.x versions, however after update to K8s v1.22.6 (GKE version v1.22.6-gke.300), gemini panics on start

```
I0215 09:33:27.399825       1 main.go:18] Running in verbose mode
I0215 09:33:27.899155       1 request.go:530] Throttling request took 99.114245ms, request: GET:https://192.168.196.1:443/apis/batch/v1?timeout=32s
I0215 09:33:28.099217       1 request.go:530] Throttling request took 299.09222ms, request: GET:https://192.168.196.1:443/apis/policy/v1?timeout=32s
I0215 09:33:28.099677       1 request.go:530] Throttling request took 299.638954ms, request: GET:https://192.168.196.1:443/apis/batch/v1beta1?timeout=32s
I0215 09:33:28.199158       1 request.go:530] Throttling request took 399.099267ms, request: GET:https://192.168.196.1:443/apis/certificates.k8s.io/v1?timeout=32s
I0215 09:33:28.199421       1 request.go:530] Throttling request took 399.357316ms, request: GET:https://192.168.196.1:443/apis/networking.k8s.io/v1?timeout=32s
I0215 09:33:28.199689       1 request.go:530] Throttling request took 399.480971ms, request: GET:https://192.168.196.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
I0215 09:33:28.200129       1 request.go:530] Throttling request took 399.808225ms, request: GET:https://192.168.196.1:443/apis/scheduling.k8s.io/v1?timeout=32s
I0215 09:33:28.349008       1 request.go:530] Throttling request took 249.806937ms, request: GET:https://192.168.196.1:443/apis/policy/v1beta1?timeout=32s
I0215 09:33:28.350454       1 request.go:530] Throttling request took 250.770056ms, request: GET:https://192.168.196.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I0215 09:33:28.399210       1 request.go:530] Throttling request took 498.899081ms, request: GET:https://192.168.196.1:443/apis/admissionregistration.k8s.io/v1?timeout=32s
I0215 09:33:28.399677       1 request.go:530] Throttling request took 549.117845ms, request: GET:https://192.168.196.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
panic: the server could not find the requested resource

goroutine 1 [running]:
github.com/fairwindsops/gemini/pkg/kube.createClient(0x42)
	/go/src/github.com/fairwindsops/gemini/pkg/kube/client.go:92 +0x66d
github.com/fairwindsops/gemini/pkg/kube.GetClient(...)
	/go/src/github.com/fairwindsops/gemini/pkg/kube/client.go:59
github.com/fairwindsops/gemini/pkg/controller.NewController(0x1d88c20)
	/go/src/github.com/fairwindsops/gemini/pkg/controller/controller.go:72 +0x5e6
main.main()
	/go/src/github.com/fairwindsops/gemini/main.go:19 +0x3d
```

### What did you expect to happen?

Most likely this is related to the `beta CustomResourceDefinition` a.k.a. `apiextensions.k8s.io/v1beta1` [API removal](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes).

### How can we reproduce this?

Deploy to K8s v1.22.x version.

### version

0.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

As a fix, I can change https://github.com/FairwindsOps/gemini/blob/3e3cc90c8a38af59ed8f179201883e93d3021304/pkg/kube/client.go#L92 to use `extClientSet.ApiextensionsV1().CustomResourceDefinitions()` and change https://github.com/FairwindsOps/gemini/blob/3e3cc90c8a38af59ed8f179201883e93d3021304/pkg/kube/client.go#L118 to use first served version. This most likely would not be a breaking change as `apiextensions.k8s.io/v1` API is available since v1.16.

**Comment by vovinacci** [comment]
Related to #48

**Comment by rbren** [comment]
Thanks @vovinacci! I agree this would work perfectly. Happy to accept a PR here

We'll probably release a new major version since it will break older k8s versions, but agree it should be a pretty straightforward upgrade.

**Comment by vovinacci** [comment]
@rbren Thanks much for the feedback. I've somehow overlooked that CRD API should also be changed. So, here we go - https://github.com/FairwindsOps/gemini/pull/58. May be a bit hard to review, sorry for that.

Tested on one of the clusters - looked OK.

**Comment by vovinacci** [comment]
@rbren @sudermanjr Thanks much for taking care! When do you plan to cut a new release? Thanks!

**Comment by rbren** [comment]
@vovinacci are you using the helm chart?

Hoping someone can confirm the latest build is working on 1.22. Should be as easy as adding `--set image.tag=build_338` to the `helm upgrade`.

**Comment by rbren** [comment]
Once we have that confirmation, we'll tag a new major version, and update the helm chart.

**Comment by lukpep** [comment]
I can confirm - it work :) 
```
I0224 08:48:33.561180       1 scheduler.go:58] Checking snapshot monitoring/grafana-pvc-backup-1643137217
I0224 08:48:33.561185       1 scheduler.go:58] Checking snapshot monitoring/grafana-pvc-backup-1643050816
I0224 08:48:33.561190       1 scheduler.go:58] Checking snapshot monitoring/grafana-pvc-backup-1642964415
I0224 08:48:33.561194       1 scheduler.go:58] Checking snapshot monitoring/grafana-pvc-backup-1642878014
I0224 08:48:33.561198       1 scheduler.go:58] Checking snapshot monitoring/grafana-pvc-backup-1642791608
I0224 08:48:33.561203       1 scheduler.go:91] need creation day false
I0224 08:48:33.561208       1 scheduler.go:91] need creation hour false
I0224 08:48:33.561212       1 groups.go:59] monitoring/grafana-pvc-backup: going to create 0, delete 0 snapshots
I0224 08:48:33.561223       1 snapshots.go:204] Deleting 0 expired snapshots
I0224 08:48:33.561228       1 groups.go:65] monitoring/grafana-pvc-backup: deleted 0 snapshots
I0224 08:48:33.561234       1 groups.go:71] monitoring/grafana-pvc-backup: created 0 snapshots
I0224 08:48:33.561243       1 controller.go:146] monitoring/grafana-pvc-backup: successfully performed backup
```

![CleanShot 2022-02-24 at 09 50 14](https://user-images.githubusercontent.com/2960580/155490626-8ec12a5d-7522-4dbb-bb93-d9f82012e5c8.png)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemini
    app.kubernetes.io/instance: in-cluster-gemini
  name: gemini-controller
  namespace: gemini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
        - command:
            - gemini
            - '-v'
            - '5'
          image: 'quay.io/fairwinds/gemini:build_338'
          imagePullPolicy: Always
          name: gemini-controller
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      serviceAccountName: gemini-controller
```

new snapshots were created after almost 2 weeks of inactivity:
```
k get volumesnapshot -n monitoring
NAME                            READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS           SNAPSHOTCONTENT                                    CREATIONTIME   AGE
....
grafana-pvc-backup-1644569713   true         grafana                             3Gi           default-snapshotclass   snapcontent-9d9b30d7-ef04-4a77-88f0-07ad95218a6b   12d            12d
grafana-pvc-backup-1645692483   true         grafana                             3Gi           default-snapshotclass   snapcontent-55d21ee1-c437-4cd6-a872-a36c670b43b0   4m37s          4m40s
```

**Comment by rbren** [comment]
🎉 cutting a release now!
